# Generated by Django 2.1.7 on 2019-04-10 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wheredoyoulive', '0005_places_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Places',
        ),
        migrations.RemoveField(
            model_name='user',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='longitude',
        ),
    ]
